entrenamiento_observatorio/gestion_usuarios/urls.py
from django.conf.urls import include, url
from django.views.generic import  TemplateView

from .views import ConfiguracionInicial, AdministradorCreateView, AdministradorDetailView, AdministradorUpdateView

extrapatters_administrador = [
    url(r'^inicial$', ConfiguracionInicial.as_view(), name='inicial'),
    url(r'^registrar$', AdministradorCreateView.as_view(), name='registrar'),
    url(r'^detalles/(?P<pk>\d+)/$', AdministradorDetailView.as_view(), name="detalles"),
    url(r'^actualizar/(?P<pk>\d+)/$', AdministradorUpdateView.as_view(), name="actualizar"),
]

"""extrapatters_estudiante = [
    url(r'^registrar-estudiante$', EstudianteCreateView.as_view(), name='registrar_estudiante'),
    url(r'^editar-estudiante/(?P<pk>\d+)/$', EstudianteUpdateView.as_view(), name='editar_estudiante'),
    url(r'^cambio-estado-estudiante/(?P<pk>\d+)/$', EstudianteCambioEstadoView.as_view(), name='cambio_estado_estudiante'),
    url(r'^listar-estudiante$', EstudianteListView.as_view(), name='listar_estudiante'),
]"""

urlpatterns = [
    url(r'^administrador/', include(extrapatters_administrador, namespace="administrador")),

]

"""
    url(r'^registrar-profesor$', ProfesorCreateView.as_view(), name='registrar_profesor'),
    url(r'^editar-profesor/(?P<pk>\d+)/$', ProfesorUpdateView.as_view(), name='editar_profesor'),
    url(r'^cambio-estado-profesor/(?P<pk>\d+)/$', ProfesorCambioEstadoView.as_view(), name='cambio_estado_profesor'),
    url(r'^listar-profesor$', ProfesorListView.as_view(), name='listar_profesor'),"""

entrenamiento_observatorio/gestion_usuarios/models.py
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

# Create your models here.
class Usuario(User):
    TIPO_IDENTIFICACION = (
        (0, 'CÉDULA DE CIUDADANÍA'),
        (1, 'CÓDIGO DE ESTUDIANTE'),
    )

    tipo_id = models.IntegerField(verbose_name='Tipo de identificación', choices=TIPO_IDENTIFICACION)
    identificacion = models.CharField(max_length=50, verbose_name='Número de identificación', unique=True)
    fecha_nacimiento = models.DateField(verbose_name='Fecha de nacimiento')
    foto = models.ImageField(upload_to='fotos_usuario/')

    class Meta:
        abstract = True



class Administrador(Usuario):

    def get_absolute_url(self):
        return reverse('gestion_usuarios:administrador:detalles',kwargs={'pk': self.id})

    class Meta:
        permissions = (
            ('list_administrador', 'Can list administrador'),
        )

entrenamiento_observatorio/gestion_usuarios/forms.py
from django import forms
from .models import Administrador
from entrenamiento_observatorio.utilities import MyDateWidget

class UsuarioCreateForm(forms.ModelForm):
    confirmar_pass = forms.CharField(required = False, widget = forms.PasswordInput(), label = "Confirmar contraseña")

    def __init__(self, *args, **kwargs):
        super(UsuarioCreateForm, self).__init__(*args, **kwargs)
        if self.instance.pk is None:
            self.fields['password'].widget = forms.PasswordInput()
        self.fields['fecha_nacimiento'].widget = MyDateWidget()

    def clean(self):
        cleaned_data = super(UsuarioCreateForm, self).clean()
        if self.instance.pk is None:
            password = cleaned_data.get('password')
            password2 = cleaned_data.get('confirmar_pass')

            if password != password2:
                msg_error = "Las contraseñas no coinciden"
                self.add_error('confirmar_pass', msg_error)
            return cleaned_data
        else:
            return cleaned_data

    def clean_identificacion(self):
        instance = getattr(self, 'instance',None)
        if instance and instance.pk:
            return instance.identificacion
        else:
            return self.cleaned_data['identificacion']

    def clean_tipo_id(self):
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            return instance.tipo_id
        else:
            return self.cleaned_data['tipo_id']

    def clean_username(self):
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            return instance.username
        else:
            return self.cleaned_data['username']


class AdministradorCreateForm(UsuarioCreateForm):

    class Meta():
        model = Administrador
        fields = ['username', 'first_name', 'last_name', 'password', 'tipo_id', 'identificacion', 'fecha_nacimiento',
                  'email', 'foto']

class AdministradorUpdateForm(AdministradorCreateForm):

    def __init__(self, *args, **kwargs):
        super(AdministradorUpdateForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['readonly'] = 1
        self.fields['tipo_id'].widget.attrs['readonly'] = 1
        self.fields['tipo_id'].widget.attrs.update({'style': 'pointer-events:none'})
        self.fields['identificacion'].widget.attrs['readonly'] = 1

    class Meta(AdministradorCreateForm.Meta):
        fields = ['username', 'first_name', 'last_name', 'tipo_id', 'identificacion', 'fecha_nacimiento',
                  'email', 'foto']

entrenamiento_observatorio/gestion_usuarios/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import CreateView, UpdateView, ListView, View, DetailView, TemplateView
from django.views.generic.edit import ModelFormMixin
from django.contrib import messages
from .models import Administrador
from .forms import  AdministradorCreateForm, AdministradorUpdateForm


# Create your views here.
class UsuarioPasswordMixin(object):

    def form_valid(self, form):
        form.instance.set_password(form.instance.password)
        messages.success(self.request, self.mensaje_exitoso)
        return super(UsuarioPasswordMixin, self).form_valid(form)

class UsuarioCreateView(UsuarioPasswordMixin, CreateView):
    pass


class UsuarioUpdateView(UsuarioPasswordMixin, UpdateView):

    def get_context_data(self, **kwargs):
        context = super(UsuarioUpdateView, self).get_context_data(**kwargs)
        context['edicion'] = True
        return context


class UsuarioListView(ListView):
    pass


class UsuarioDetailView(DetailView):
    pass


class UsuarioCambioEstadoMixin(ModelFormMixin):

   def get(self, *args, **kwargs):
       usuario = get_object_or_404(self.model, pk=kwargs['pk'])
       usuario.is_active = not usuario.is_active
       usuario.save()
       return redirect(usuario.get_absolute_url())


class ConfiguracionInicial(View):

    def get(self, *args, **kwargs):
        admins = Administrador.objects.all()
        print(admins)
        if len(admins) >= 0:
            messages.info(self.request, 'Por favor cree el administrador.')
            return redirect('gestion_usuarios:administrador:registrar')
        else:
            messages.warning(self.request, 'Ya existe un administrador.')
            return redirect('inicio')


class AdministradorCreateView(UsuarioCreateView):
    """
    Abril 8 de 2015
    Autor: Carolina Guzmán

    Crea el usuario administrador
    Hereda de la clase general UsuarioCreateView
    A partir de POST se obtiene la información para crear un usuario administrador y se almacena en la base de datos.
    Si el usuario se crea exitosamente se envia un mensaje tipo success y se redirecciona a la página de inicio.

    :param request: Petición Realizada
    :type request:    WSGIRequest
    """
    model = Administrador
    form_class = AdministradorCreateForm
    template_name = "gestion_usuarios/usuario_form.html"
    mensaje_exitoso = "Administrador creado exitosamente!"

    def get_success_url(self):
        return reverse('login')

    def get(self, *args, **kwargs):
        admins = Administrador.objects.all()
        if len(admins) > 2:
            messages.warning(self.request, 'Ya existe un administrador.')
            return redirect('login')
        else:
            return super(AdministradorCreateView, self).get(*args, **kwargs)


class AdministradorDetailView(UsuarioDetailView):
    model = Administrador


class AdministradorUpdateView(UsuarioUpdateView):
    model = Administrador
    form_class = AdministradorUpdateForm
    template_name = "gestion_usuarios/usuario_form.html"
    mensaje_exitoso = "Administrador actualizado exitosamente!"

entrenamiento_observatorio/templates/gestion_usuarios/administrador_detail.html
{% extends 'gestion_usuarios/usuario_detail.html' %}

{% block titulo %}Detalles Administrador{% endblock titulo %}

{% block url_detalles %}
{% url 'gestion_usuarios:administrador:detalles' object.id %}
{% endblock url_detalles %}

{% block tipo_usuario %} Administrador {% endblock tipo_usuario %}

{% block mas_detalles %}
    <li class="list-group-item">
        <span class="pull-right"> <a href="{% url 'gestion_usuarios:administrador:actualizar'  object.id %}">Modificar información</a> </span>
    </li>
{% endblock mas_detalles%}

entrenamiento_observatorio/templates/gestion_usuarios/usuario_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block miga_pan %}
    <li><a href="{% url 'inicio' %}">Inicio</a></li>
    <li><a href="#">Gestión de usuarios</a>
    <li class="active">Detalles del perfil</li>
{% endblock miga_pan %}

{% block titulo_pagina %}
Detalles {{ user.get_full_name | capfirst }}
{% endblock titulo_pagina %}

{% block titulo %}
    Detalles Usuario
{% endblock titulo %}

{% block contenido %}
    <div class="col-lg-10 col-lg-offset-1">
        <div class="ibox float-e-margins">
            <div class="ibox ">
                <div class="ibox-content">
                    <div class="tab-content">
                        <div id="contact-1" class="tab-pane active">
                            <div class="row m-b-lg">
                                <div class="col-lg-4 text-center">
                                    <h2>{{ object.get_full_name | capfirst }}</h2>

                                    <div class="m-b-sm">
                                        <img alt="image" class="img-circle" src="{{ object.foto.url }}"
                                             style="width: 62px">
                                    </div>
                                </div>

                            </div>
                            <div class="client-detail">
                            <div class="full-height-scroll">

                                <strong>{% block tipo_usuario %} {% endblock tipo_usuario %}</strong>

                                <ul class="list-group clear-list">
                                    <li class="list-group-item fist-item">
                                        Usuario
                                        <span class="pull-right">  {{ object.username  }} </span>
                                    </li>
                                    <li class="list-group-item">
                                        Correo Electrónico
                                        <span class="pull-right"> {{ object.email }} </span>
                                    </li>
                                    <li class="list-group-item">
                                        Tipo de identificación
                                        <span class="pull-right"> {{ object.get_tipo_id_display | lower | capfirst}} </span>

                                    </li>
                                    <li class="list-group-item">
                                        Identificación
                                        <span class="pull-right"> {{ object.identificacion }} </span>
                                    </li>
                                    <li class="list-group-item">
                                        Fecha de nacimiento
                                        <span class="pull-right"> {{ object.fecha_nacimiento | date }} </span>
                                    </li>
                                    {% block mas_detalles %}
                                    {% endblock mas_detalles%}
                                </ul>
                            </div>
                            </div>
                        </div>
                    </div>
                    </div>
            </div>
        </div>
    </div>
{% endblock contenido %}

entrenamiento_observatorio/templates/gestion_usuarios/usuario_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block miga_pan %}
    <li><a href="{% url 'inicio' %}">Inicio</a></li>
    <li><a href="#">Gestión de usuarios</a>
    {% if not edicion %}
        <li class="active"> Registrar</li>
    {% else %}
        <li class="active"> Actualizar </li>
    {% endif %}
{% endblock miga_pan %}


{% block titulo_pagina %}
    {% if not edicion %}
        Registrar Usuario
    {% else %}
        Actualizar Usuario
    {% endif %}
{% endblock titulo_pagina %}

{% block titulo %}
    {% if not edicion %}
        Registrar Usuario
    {% else %}
        Actualizar Usuario
    {% endif %}
{% endblock titulo %}

{% block contenido %}
    <div class="col-lg-10 col-lg-offset-1">
        <div class="ibox float-e-margins">
            <div class="ibox-content">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <form action="" method="POST" class="form-horizontal" enctype="multipart/form-data" id="usuario-form">{% csrf_token %}
                            {% bootstrap_field form.first_name  %}
                            {% bootstrap_field form.last_name  %}
                            {% bootstrap_field form.username  %}
                            {% if not edicion %}
                                {% bootstrap_field form.password  %}
                                {% bootstrap_field form.confirmar_pass  %}
                            {% endif %}
                            {% bootstrap_field form.tipo_id  %}
                            {% bootstrap_field form.identificacion  %}
                            {% bootstrap_field form.fecha_nacimiento  %}
                            {% bootstrap_field form.email  %}
                            {% bootstrap_field form.foto  %}
                            {% if not edicion %}
                                {% bootstrap_button "Registrar" button_type="submit" button_class="btn-primary"%}
                            {% else %}
                                {% bootstrap_button "Actualizar" button_type="submit" button_class="btn-primary"%}
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock contenido %}

entrenamiento_observatorio/templates/gestion_usuarios/usuario_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block miga_pan %}
    <li><a href="{% url 'inicio' %}">Inicio</a></li>
    <li><a href="#">Gestión de usuarios</a>
    <li class="active">Listar</li>
{% endblock miga_pan %}

{% block titulo_pagina %}
    Registrar Usuario
{% endblock titulo_pagina %}

{% block titulo %}
    Registrar Usuario
{% endblock titulo %}

{% block contenido %}
    <div class="col-lg-10 col-lg-offset-1">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Listar Usuarios</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>

                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>

            <div class="ibox-content">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover" id="tabla-usuarios">
                                <thead>
                                    <tr>
                                        <th>Nombres</th>
                                        <th>Apellidos</th>
                                        <th>Nombre de usuario</th>
                                        <th>Correo electrónico</th>
                                        <th>Estado</th>
                                        <th>Opciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for usuario in object_list %}
                                        <tr>
                                            <td>{{ usuario.first_name }}</td>
                                            <td>{{ usuario.last_name }}</td>
                                            <td>{{ usuario.username }}</td>
                                            <td>{{ usuario.email }}</td>
                                            <td>{% if usuario.is_active %}
                                                    <label class="label label-primary">ACTIVO</label>
                                                {% else %}
                                                    <label class="label label-danger">INACTIVO</label>
                                                {% endif %}
                                            </td>
                                            <td>
                                                <div class="btn-group">
                                                    {% block opciones_usuario %}
                                                    <button data-toggle="dropdown" class="btn btn-success dropdown-toggle" aria-expanded="false">Opciones <span class="caret"></span></button>
                                                    <ul class="dropdown-menu">
                                                        <li><a href="#" class="font-bold"><i class="fa fa-eye text-success"></i> Ver más</a></li>
                                                        <li><a href="{% url 'gestion_usuarios:editar' usuario.id %}" class="font-bold"><i class="fa fa-edit text-info"></i> Editar</a></li>
                                                        <li><a href="{% url 'gestion_usuarios:cambio_estado' perfilusuario.id %}" class="font-bold"><i class="fa fa-ban text-danger"></i> Cambiar estado</a></li>
                                                    </ul>
                                                    {% endblock %}
                                                </div>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock contenido %}

{% block javascript %}
    <script>
        var id_datatable = '#tabla-usuarios';
    </script>
    <script src="{% static 'js/personalizado/generar_datatable.js' %}"></script>
{% endblock javascript %}